global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "probpf"
    static_configs:
      - targets: ["localhost:8080"]
        labels:
          instance: "probpf-main"
    scrape_interval: 15s
    scrape_timeout: 10s
